"""Lightweight constants for reconciliation matching."""

MATCH_TYPE_EXACT = "exact"
MATCH_TYPE_FUZZY = "fuzzy"
MATCH_TYPE_SPLIT = "split"
MATCH_TYPE_UNMATCHED = "unmatched"

MATCH_STATUS_AUTO_MATCHED = "auto_matched"
MATCH_STATUS_CANDIDATE = "candidate"
MATCH_STATUS_AMBIGUOUS = "ambiguous"
MATCH_STATUS_UNMATCHED = "unmatched"

RECONCILIATION_RUN_STATUS_COMPLETED = "completed"

__all__ = [
    "MATCH_STATUS_AMBIGUOUS",
    "MATCH_STATUS_AUTO_MATCHED",
    "MATCH_STATUS_CANDIDATE",
    "MATCH_STATUS_UNMATCHED",
    "MATCH_TYPE_EXACT",
    "MATCH_TYPE_FUZZY",
    "MATCH_TYPE_SPLIT",
    "MATCH_TYPE_UNMATCHED",
    "RECONCILIATION_RUN_STATUS_COMPLETED",
]
